import countTrue from './index';

describe('Javascript - Medium - 1', () => {
  test('How Much is True?', () => {
    expect(countTrue([true, false, false, true, false])).toEqual(2);
    expect(countTrue([false, false, false, false])).toEqual(0);
    expect(countTrue([])).toEqual(0);
    expect(
      countTrue([
        false,
        false,
        true,
        true,
        false,
        false,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
      ])
    ).toEqual(8);
    expect(
      countTrue([true, false, true, true, false, false, false, false, false])
    ).toEqual(3);
    expect(
      countTrue([
        false,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
      ])
    ).toEqual(8);
    expect(
      countTrue([
        true,
        false,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        false,
      ])
    ).toEqual(6);
    expect(
      countTrue([
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        false,
        true,
        false,
        false,
      ])
    ).toEqual(3);
    expect(
      countTrue([
        true,
        false,
        false,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false,
      ])
    ).toEqual(3);
    expect(
      countTrue([
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
      ])
    ).toEqual(4);
    expect(
      countTrue([
        true,
        false,
        true,
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        false,
        true,
        false,
      ])
    ).toEqual(9);
    expect(
      countTrue([
        true,
        false,
        true,
        true,
        true,
        true,
        false,
        true,
        true,
        false,
        true,
        false,
        false,
        false,
        false,
      ])
    ).toEqual(8);
    expect(
      countTrue([
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        true,
        true,
        false,
        true,
      ])
    ).toEqual(6);
  });
});
